### ISSUE TITLE
Add `Project.toml` and `Manifest.toml`

### ISSUE THREAD

**Issue by mszep** [jarvist/Quante.jl#8]
It seems like specifying dependencies in a `REQUIRE` file is outdated, with the modern approach being to have two files, `Project.toml` and `Manifest.toml` (see https://docs.julialang.org/en/v1/stdlib/Pkg/).

Things seem to work for now, but this should probably be changed sooner or later -- there might also be other changes that need to be made that I'm not aware of from a quick reading of the `Pkg` documentation.

**Comment by jarvist** [comment]
Apologies for the late reply! Resolved with 5e5306f642a1a0d455f4bffa027ab44e20f9a697.
