### ISSUE TITLE
'Warning: Package Quante does not have Test in its dependencies' when using  with julia 1.6

### ISSUE THREAD

**Issue by mgr327** [jarvist/Quante.jl#9]
When using with Julia 1.6:

julia> using Quante
[ Info: Precompiling Quante [cffb2240-8e2b-11e9-2857-d3cff796b0cb]
 Warning: Package Quante does not have Test in its dependencies:
.......

the issue is too small for a pull request ...

**Comment by jarvist** [comment]
Thanks! 
Hopefully resolved with eec27a6fd75ac7fb494e59aaa2d203ebfec10cec - Pkg3 confuses me a lot, but it doesn't error any more.
